### ISSUE TITLE
not working with es6

### ISSUE THREAD

**Issue by Bnaimy** [peakchen90/babel-plugin-react-directives#2]
hi I am really like this project because is very difficult to write code without directive
I really I don't know why is not working ,
just if you can init a project with configuration of your project ??

**Comment by peakchen90** [comment]
@Bnaimy 
Thank you for using and like it.
Can you provide the babel configuration, code, error logs? Provide screenshots is better.

**Comment by Bnaimy** [comment]
this is file babelrc inside package.json

`{
    "name": "app",
    "version": "1.0.0",
    "babel": {
      "presets": [ ],
      "plugins": ["react-directives"],
      "options": {
                "prefix": "x",
                "pragmaType": "React"
                 }
    }`

**Comment by peakchen90** [comment]
@Bnaimy 
Your babel configuration looks like this:
```json
{
  "name": "app",
  "version": "1.0.0",
  "babel": {
    "presets": [],
    "plugins": [
      "react-directives"
    ],
    "options": {
      "prefix": "x",
      "pragmaType": "React"
    }
  }
}
```

It is invalid, correct configuration:
```json
{
  "name": "app",
  "version": "1.0.0",
  "babel": {
    "presets": [],
    "plugins": [
      [
        "react-directives",
        {
          "prefix": "x",
          "pragmaType": "React"
        }
      ]
    ]
  }
}
```

You can learn more at [https://babeljs.io/docs/en/plugins#plugin-options](https://babeljs.io/docs/en/plugins#plugin-options), and optimize the documentation later.

**Comment by Bnaimy** [comment]
it's work thanks and waiting for features good jobs
